owner: dame-senders
repo: senders-status
userAgent: dame-senders
sites:
  - name: Senders Portal
    url: https://portal.senders.ai
  - name: Senders MCP API
    url: https://mcp.senders.ai/health
  - name: Senders Main Site
    url: https://senders.ai
  - name: Senders Newsletter
    url: https://mxa.aledamail.com
status-website:
  cname: status.senders.ai
  name: Senders Status
